config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  #resources :search_suggestions
  resources :likes
  resources :notifications, only: [:index, :update]
  resources :posts
  resources :usuarios, as: :users, only: [:show, :update] do
    member do
      get :friends
    end
  end
  resources :friendships
  resources :comments

  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/search", to: "search_people#search"
  #Ruta para manejar las sugerencias de busqueda.
  post "/search_people/search_suggestions", to: "search_people#search_suggestions"


  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/partials/_nav.haml
%nav
  .navbar-toggleable-xs.collapse#bd-main-nav{:"aria-expanded" => :false}
    =link_to "DeSoft-Co", root_path, class:"navbar-brand"
    %ul.nav.navbar-nav.float-xs-right
      -if user_signed_in?
        %li.nav-item
          /#notifications.shadow
          .relative
            =link_to notifications_path, class:"nav-link", id:"" do
              %i.fa.fa-bell.fa-1x{:"aria-hidden" => :true}
              Notificaciones
              %span#notification.my-badge.pink{style:("visibility: hidden;" if current_user.unviewed_notifications_count == 0)}=current_user.unviewed_notifications_count
        %li.nav-item
          .relative
            =link_to "friendships", class:"nav-link" do
              %i.fa.fa-users.fa-1x{:"aria-hidden" => :true}
              Solicitudes
              %span#friendships.my-badge.pink{style:("visibility: hidden;" if @friend_request == 0)}=@friend_request
        %li.nav-item
          .relative
            =link_to "friendships", class:"nav-link" do
              %i.fa.fa.fa-inbox.fa-1x{:"aria-hidden" => :true}
              Mensajes
              %span#friendships.my-badge.pink{style:("visibility: hidden;" if @friend_request == 0)}=@friend_request
        %li.nav-item.dropdown
          #config-account.cover.rounded{:"data-toggle" => :dropdown, :"aria-haspopup" => :true, :"aria-expanded" => :false, style:"background-image: url(#{current_user.avatar.url(:thumb)});width:30px;height:30px;"}
          .dropdown-menu.dropdown-menu-right.dropdown-nav{:"aria-labelledby" => :"config-account"}
            =link_to current_user, class:"dropdown-item" do
              %i.fa.fa-user.font-icon{:"aria-hidden" => :true}
              Perfil
            .dropdown-divider
            =link_to destroy_user_session_path, method: :delete,class:"dropdown-item" do
              %i.fa.fa-sign-out.font-icon{:"aria-hidden" => :true}
              Cerrar sesión

    =form_tag({controller:"search_people", action:"search"}, method:"get", class:"row", id:"form-search") do
      .col-xs-6.col-sm-7.col-md-8.col-lg-10
        %table.full-width
          %tr
            %td
              /%input#search.form-control{type:"text", placeholder:"Buscar personas"}
              =text_field_tag "search", nil, name:"term", class:"form-control", placeholder:"Buscar personas", autocomplete:"off"
              /Aquí van las sugerencias de busqueda
              .full-width.relative
                .list-group.full-width.absolute#result
            %td
              %a{href:"javascript:{}", onclick:"document.getElementById('form-search').submit(); return false;"}
                %i.fa.fa-search.text-white{:"aria-hidden" => :true}