config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  #resources :search_suggestions
  resources :likes
  resources :notifications, only: [:index, :update]
  resources :posts
  resources :usuarios, as: :users, only: [:show, :update] do
    member do
      get :friends
    end
  end
  resources :friendships
  resources :comments

  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/search", to: "search_people#search"
  #Ruta para manejar las sugerencias de busqueda.
  post "/search_people/search_suggestions", to: "search_people#search_suggestions"


  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  item_type  :string
#  item_id    :integer
#  viewed     :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
  after_create_commit { NotificationBroadcastJob.perform_later(self) }
  scope :unviewed, ->{ where(viewed:false) }
  scope :latest, ->{ order("created_at desc").limit(10) }

  def self.for_user(user_id)
    Notification.where(user_id: user_id).unviewed.count
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  	@notifications = Notification.where(user:current_user).unviewed.latest
  	respond_to do |format|
  		format.html
  		format.js
  	end
  end

  def update
  	@notification = Notification.find(params[:id])
    respond_to do |format|
    	if @notification.update(notification_params)
    		format.html { redirect_to :back, notice: "Notificación marcada." }
        format.js {  }
    	else
    		format.html { redirect_to :back, error: "Ocurrio un error :(" }
    	end
    end
  end

  private
  	def notification_params
  		params.require(:notification).permit(:viewed)
  	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def render_notifications(notifications)
		notifications.map do |notification|
			render partial:"notifications/#{notification.item_type.downcase}", locals: {notification: notification}
		end.join("").html_safe
	end
end

app/views/notifications/_comment.haml
%li.list-group-item{:id => "notification-#{notification.id}"}
	%table.text-space
		%tr
			%td
				=circle_img notification.item.user.avatar.url(:thumb),30
			%td.padding-left
				%b=link_to notification.item.user.name, notification.item.user
			%td
				comento tu
				=notification.item.item_type
			%td.padding-left
				=link_to notification_path(id: notification.id, notification:{viewed: true}), remote: true, method: :put do
					%i.fa.fa-check.fa-lg.text-success{:"aria-hidden" => :true}

app/views/notifications/_like.haml
%li.list-group-item{:id => "notification-#{notification.id}"}
	%table.text-space
		%tr
			%td
				=circle_img notification.item.user.avatar.url(:thumb),30
			%td.padding-left
				A
				%b
					=link_to notification.item.user.name, notification.item.user
			%td
				le gusta tu
				=notification.item.item_type
			%td.padding-left
				=link_to notification_path(id: notification.id, notification:{viewed: true}), remote: true, method: :put do
					%i.fa.fa-check.fa-lg.text-success{:"aria-hidden" => :true}

app/views/notifications/_post.haml
%li.list-group-item
	%table
		%tr
			%td
				=circle_img notification.item.user.avatar.url(:thumb),30
			%td.padding-left
				%b
					=notification.item.user.name
			%td
				Creó una nueva publicación
			%td.padding-left
				=link_to notification_path(id: notification.id, notification:{viewed: true}), method: :put do
					%i.fa.fa-check.fa-lg.text-success{:"aria-hidden" => :true}

app/views/notifications/index.html.haml
.row.center-xs
	.col-sx-12.col-sm-10.col-md-8.col-lg-8
		.box
			.card
				%h4.card-header Notificaciones
				.card-block
					%ul.list-group
						-if @notifications.empty?
							%p.card-text.text-muted No tienes nuevas notificaciones
						=render_notifications @notifications