config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do

  #resources :search_suggestions
  resources :likes
  resources :notifications, only: [:index, :update]
  resources :posts
  resources :usuarios, as: :users, only: [:show, :update] do
    member do
      get :friends
    end
  end
  resources :friendships
  resources :comments

  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks"
  }
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/search", to: "search_people#search"
  #Ruta para manejar las sugerencias de busqueda.
  post "/search_people/search_suggestions", to: "search_people#search_suggestions"


  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
  	root 'main#unregistered'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	before_action :set_user
	before_action :authenticate_user!, only: [:update]
	before_action :authenticate_owner!, only: [:update]

	def show
		@are_friends = current_user.my_friend?(@user)
		@posts = @user.posts.nuevos.paginate(page:params[:page], per_page:15)
		@count_likes = User.count_likes_for_user(current_user.id)
		@count_friends = Friendship.friendships_of_a_user(@user).count
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user }
				format.json { render :show, status: :created, location: @user }
				format.js
			else
				format.html { redirect_to @user, notice:"Error al actualizar" }
				format.json { render json: @user.errors }
			end
		end
	end
	#Obtiene los amigos del usuario que se selecciono
	def friends
		@friends = User.friends(@user)
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def authenticate_owner!
			if current_user != @user
				redirect_to root_path, notice: "No estás autorizado", status: :unauthorized
			end
		end

		def user_params
			#params.require(:post).permit(:body)
			params.require(:user).permit(:email, :username, :name, :bio, :avatar, :cover)
		end
end

app/views/usuarios/_menu_avatar.haml
/.absolute{style:"top:6px;right:6px;"}
/	%button.mdl-button.white-text.mdl-js-button.mdl-button--icon#user-menu-avatar-left
/		%i.material-icons more_vert
/	%ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{for:"/user-menu-avatar-left"}
/		%li.mdl-menu__item.file-activate{for:"#user_avatar"} Actualizar avatar
/		%li.mdl-menu__item.file-activate{for:"#user_cover"} Actualizar cover

.absolute{style:"top:6px;right:6px;"}
	%button.btn.btn-outline-secondary.btn-sm#btn-user-cover{:type => :button, :for => "#user_cover"}
		%i.fa.fa-camera.file-active{:"aria-hidden" => :true}

app/views/usuarios/friends.haml
.top-space
  .row.center-xs
    .col-lg-10.small-padding.white.card
      .row
        -@friends.each do |friend|
          .col-xs-12.col-sm-10.col-md-6.col-lg-3
            =circle_img friend.avatar.url(:medium), 150
            .small-padding
              %b=link_to friend.name, friend

app/views/usuarios/show.haml
.profile-header-photo{style:("background-image:url(#{@user.cover.url(:medium)});" if @user.cover_file_name != nil)}
	.profile-header-photo-in
		.tbl-cell
			.info-block
				.container-fluid
					.row
						.col-xs-9.col-xs-offset-3.col-lg-8.col-md-offset-0
							.tbl.info-tbl
								.tbl-row
									.tbl-cell
										%p.title
											%span= best_in_place_if current_user == @user, @user, :name
										%p Founder DS
									.tbl-cell.tbl-cell-stat
										.inline-block
											.title=@count_friends
											%p=link_to "Amigos", friends_user_path, class:"white-text no-line hover-white"
									.tbl-cell.tbl-cell-stat
										.inline-block
											%p.title=@count_likes
											%p Likes
									.tbl-cell.tbl-cell-stat
										.inline-block
											%p.title=@user.posts.count
											%p Posts

	/Boton cover
	=button_update_cover @user
/.profile-header-photo
.invisible
	=form_for @user, remote: true do |f|
		= f.file_field :avatar, class:"remotipart"
	=form_for @user, remote: true do |f|
		= f.file_field :cover, class:"remotipart"

/Barra lateral izquierda
.container-fluid
	.row
		.col-xs-2.col-lg-3
			%aside.profile-side
				%section.box-typical.profile-side-user
					/%button.avatar-preview.avatar-preview-128{type:"button"}
					/	=circle_img @user.avatar.url(:medium),150
					/	%span.update
					/		%i.fa.fa-picture-o
					/		Update photo
					/	%input{type:"file"}
					=button_update_avatar @user
					-if @are_friends
						%button.btn.btn-info{type:"button"} Enviar mensaje
					.top-space
					-unless @are_friends
						=button_to friendships_path(friend_id: @user.id),method: :post,remote: true, :"data-type" => "script", class:"btn btn-outline-info" do
							Agregar
					/%button.btn.btn-outline-info Agregarbtn.btn-outline-info

					/.bottom-txt Standing: 154
				%section.box-typical.profile-side-stat
					.tbl
						.tbl-row
							.tbl-cell
								%span.number=@user.followers.count
								Seguidores
							.tbl-cell
								%span.number=@user.followed.count
								Seguidos
				%section.box-typical
					%header.box-typical-header-sm.bordered Estado
					.box-typical-inner
						%p
							%span.text-muted.text-italics= best_in_place_if current_user == @user, @user, :bio
		.col-xs-10.col-lg-9
			.box.text-left
				=render @posts

:javascript
	$(document).ready(function () { $(".best-in-place").best_in_place(); });
	$("#btn-user-cover").click(function(){
		$( "#user_cover" ).click();
	});
	$("#btn-user-avatar").click(function(){
		$( "#user_avatar" ).click();
	});